const List materis = [
  {
    "id": 1,
    "judul": "BAB 1 Berbagai Jenis Peralatan Teknologi Informasi dan Komunikasi",
    "gambar": "assets/images/materi/hardware.png",
    "video": "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    "materi": "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    "id": 2,
    "judul": "BAB 2 Sejarah Perkembangan Teknologi Informasi dan Komunikasi",
    "gambar": "assets/images/materi/hardware.png",
    "video": "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    "materi": "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    "id": 3,
    "judul": "BAB 3 Peranan Teknologi Informasi dan Komunikasi dalam Kehidupan",
    "gambar": "assets/images/materi/hardware.png",
    "video": "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    "materi": "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    "id": 4,
    "judul": "BAB 4 Dampak Negatif dari Penggunaan Teknologi Informasi dan Komunikasi",
    "gambar": "assets/images/materi/hardware.png",
    "video": "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    "materi": "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    "id": 5,
    "judul": "BAB 5 Mengoperasikan Komputer dengan Prosedur yang Benar",
    "gambar": "assets/images/materi/hardware.png",
    "video": "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    "materi": "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    "id": 6,
    "judul": "BAB 6 Operasi Dasar pada Sistem Operasi",
    "gambar": "assets/images/materi/hardware.png",
    "video": "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    "materi": "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    "id": 7,
    "judul": "BAB 7 Perangkat Keras Komputer",
    "gambar": "assets/images/materi/hardware.png",
    "video": "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    "materi": "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    "id": 8,
    "judul": "BAB 8 Perangkat Lunak Komputer",
    "gambar": "assets/images/materi/hardware.png",
    "video": "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    "materi": "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    "id": 9,
    "judul": "BAB 9 Pemakaian Program Aplikasi Pengolah Kata",
    "gambar": "assets/images/materi/hardware.png",
    "video": "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    "materi": "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
];